### ISSUE TITLE
How to provide credentials for MinIO

### ISSUE THREAD

**Issue by drauschenbach** [nidor1998/s3sync#20]
I see there is support for an endpoint override, which enables me to point at my local MinIO object storage. But I don't see where I can set a user/pass (aka api-key/secret-key). I tried `s3://user:pass@bucket` but it didn't work. Any advice? Or will this need to become a feature request?

**Comment by nidor1998** [comment]
You can use '--source-access-key/--source-secret-access-key' or '--target-access-key/--target-secret-access-key' or AWSCLI profile(default).

Please check 's3sync --help'. 

I have never used MinIO. so, I don't know what parameters required. But you will need specify endpoint_url and '--source-force-path-style/--target-force-path-style'(maybe)

**Comment by drauschenbach** [comment]
Works. Thanks!
